default: &default
  adapter: mysql2
  host: localhost
  port: 3306
  username: root
  password: bitlasoft
  encoding: utf8
  reconnect: false
  pool: 5
  min_messages: ERROR
development:
  <<: *default 
  database: flight-booking-dev
production: 
  <<: *default
  database: <%= ENV['PRODUCTION_DATABASE'] %>
  username: <%= ENV['DATABASE_USERNAME'] %> 
  password: <%= ENV['DATABASE_PASSWORD'] %>